name: Fetch Latest Tweet from @DarkSoulsGame

on:
  workflow_dispatch:  # Allows manual execution

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci  # Ensures a clean and fast installation

      - name: Run script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "false"  # Ensures Puppeteer works in CI
        run: node tweet-scraper-dark-souls.js
